apiVersion: v1
kind: Pod
metadata:
  labels:
    run: app1
  name: app1
  annotations:
    dapr.io/enabled: "true"
    dapr.io/app-id: "app1"
    dapr.io/enable-api-logging: "true"
spec:
  containers:
  - image: srinman/netshoot
    name: mypod
    command: ["sh","-c","sleep 3000"]
  restartPolicy: Always
